name: Deploy API

on:
  push:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Nexus
      run: |
        mvn -s ~/.m2/settings.xml clean deploy
